name: Gerrit CI testing
on:
  workflow_dispatch: {} #todo, input variables here
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lineageos-infra/fetch-gerrit-change@main
        with:
          repository: LineageOS/hudson
          gerrit-ref: refs/changes/05/366405/1
          ref: 05e08dfe5169fcedfe424a53e46e38ff292beeba
      - name: test
        run: |
          cat README
      # your action runs here
