name: Gerrit CI testing
on:
  workflow_dispatch: 
    inputs:
      ref: 
        type: string
      gerrit-ref:
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lineageos-infra/fetch-gerrit-change@main
        with:
          repository: LineageOS/hudson
          gerrit-ref: ${{ inputs.gerrit-ref }}
          ref: ${{ inputs.ref }}
      - name: test
        run: |
          cat README
      # your action runs here
